inv_settings = {
    "message_edit": {
        "enabled": False,
        "channel": None,
        "bots": False,
        "colour": 3027255,
        "emoji": "\N{MEMO}",
        "embed": True,
    },
    "message_delete": {
        "enabled": False,
        "channel": None,
        "bots": False,
        "bulk_enabled": False,
        "bulk_individual": False,
        "cached_only": True,
        "colour": 3027255,
        "emoji": "\N{WASTEBASKET}\N{VARIATION SELECTOR-16}",
        "embed": True,
    },
    "user_change": {
        "enabled": False,
        "channel": None,
        "colour": 3027255,
        "bots": True,
        "nicknames": True,
        "emoji": "\N{MAN}\N{ZERO WIDTH JOINER}\N{WRENCH}",
        "embed": True,
    },
    "role_change": {
        "enabled": False,
        "channel": None,
        "colour": 3027255,
        "emoji": "\N{WAVING WHITE FLAG}\N{VARIATION SELECTOR-16}",
        "embed": True,
    },
    "role_create": {
        "enabled": False,
        "colour": 3027255,
        "channel": None,
        "emoji": "\N{WAVING WHITE FLAG}\N{VARIATION SELECTOR-16}",
        "embed": True,
    },
    "role_delete": {
        "enabled": False,
        "colour": 3027255,
        "channel": None,
        "emoji": "\N{WAVING WHITE FLAG}\N{VARIATION SELECTOR-16}",
        "embed": True,
    },
    "voice_change": {
        "enabled": False,
        "channel": None,
        "colour": 3027255,
        "emoji": "\N{MICROPHONE}",
        "embed": True,
        "bots": False,
    },
    "user_join": {
        "enabled": False,
        "channel": None,
        "colour": 3027255,
        "emoji": "\N{INBOX TRAY}\N{VARIATION SELECTOR-16}",
        "embed": True,
    },
    "user_left": {
        "enabled": False,
        "channel": None,
        "colour": 3027255,
        "emoji": "\N{OUTBOX TRAY}\N{VARIATION SELECTOR-16}",
        "embed": True,
    },
    "channel_change": {
        "enabled": False,
        "channel": None,
        "colour": 3027255,
        "emoji": "",
        "embed": True,
    },
    "channel_create": {
        "enabled": False,
        "channel": None,
        "colour": 3027255,
        "emoji": "",
        "embed": True,
    },
    "channel_delete": {
        "enabled": False,
        "channel": None,
        "colour": 3027255,
        "emoji": "",
        "embed": True,
    },
    "guild_change": {
        "enabled": False,
        "channel": None,
        "colour": 3027255,
        "emoji": "\N{HAMMER AND WRENCH}\N{VARIATION SELECTOR-16}",
        "embed": True,
    },
    "emoji_change": {
        "enabled": False,
        "channel": None,
        "colour": 3027255,
        "emoji": "",
        "embed": True,
    },
    "commands_used": {
        "enabled": False,
        "channel": None,
        "privs": ["MOD", "ADMIN", "BOT_OWNER", "GUILD_OWNER"],
        "colour": 3027255,
        "emoji": "\N{ROBOT FACE}",
        "embed": True,
    },
    "invite_created": {
        "enabled": False,
        "channel": None,
        "colour": 3027255,
        "emoji": "",
        "embed": True,
    },
    "invite_deleted": {
        "enabled": False,
        "channel": None,
        "colour": 3027255,
        "emoji": "",
        "embed": True,
    },
    "ignored_channels": [],
    "invite_links": {},
}
